/**
 * THIS FILE IS GENERATED AUTOMATICALLY.
 * DO NOT EDIT.
 *
 * You are probably looking on adding initialization code.
 * Use "quasar new plugin <name>" and add it there.
 * One plugin per concern. Then reference the file(s) in quasar.conf.js > plugins:
 * plugins: ['file', ...] // do not add ".js" extension to it.
 **/

import 'quasar-framework/dist/quasar.ie.polyfills'

import Vue from 'vue'
import Quasar, {
  CloseOverlay,
  Dialog,
  Loading,
  Notify,
  QAutocomplete,
  QBtn,
  QBtnDropdown,
  QBtnGroup,
  QCard,
  QCardActions,
  QCardMain,
  QCardSeparator,
  QCardTitle,
  QCheckbox,
  QChip,
  QCollapsible,
  QDatetime,
  QField,
  QIcon,
  QInnerLoading,
  QInput,
  QInputFrame,
  QItem,
  QItemMain,
  QItemSeparator,
  QItemSide,
  QItemTile,
  QLayout,
  QLayoutDrawer,
  QLayoutFooter,
  QLayoutHeader,
  QList,
  QListHeader,
  QModal,
  QPage,
  QPageContainer,
  QPageSticky,
  QPagination,
  QPopover,
  QResizeObservable,
  QSelect,
  QSlider,
  QSpinner,
  QTab,
  QTabPane,
  QTabs,
  QToggle,
  QToolbar,
  QToolbarTitle,
  QTooltip,
  QUploader,
  Ripple
} from 'quasar'

Vue.use(Quasar, {
  components: {
    QCard,
    QCardMain,
    QCardTitle,
    QCardSeparator,
    QCardActions,
    QInput,
    QField,
    QLayout,
    QLayoutHeader,
    QLayoutFooter,
    QLayoutDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QListHeader,
    QItem,
    QItemTile,
    QItemMain,
    QItemSide,
    QItemSeparator,
    QCollapsible,
    QChip,
    QToggle,
    QSelect,
    QPagination,
    QModal,
    QInputFrame,
    QCheckbox,
    QDatetime,
    QTabs,
    QTab,
    QTabPane,
    QAutocomplete,
    QSlider,
    QBtnDropdown,
    QPageSticky,
    QResizeObservable,
    QTooltip,
    QPopover,
    QSpinner,
    QUploader,
    QBtnGroup,
    QInnerLoading
  }, directives: {Ripple, CloseOverlay}, plugins: {Dialog, Notify, Loading}
})
